### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by pluddle** [apexad/homebridge-mysmartblinds-bridge#109]
Installed the plugin, input login credentials and then restart Homebridge, but I'm getting an error straight away!

Homebridge v1.3.4
Node.js v16.6.2
Npm Version v7.20.3

**Logs**
```
[16/08/2021, 18:22:42] [MySmartBlindsBridge] authToken refresh, now expires 2021-08-17T03:22:42.000Z
Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at /usr/lib/node_modules/homebridge-mysmartblinds-bridge/src/platform.ts:146:96
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-mysmartblinds-bridge/src/platform.ts:144:24
    at tryCatcher (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)

```

**Comment by apexad** [comment]
Do you have the bridge? https://www.mysmartblinds.com/products/smart-hub

**Comment by pluddle** [comment]
Yes, bridge is connected and working on the MySmartBlinds app.

**Comment by pluddle** [comment]
This was a misunderstanding on how this integration works, hub added, blinds added but I had not created any rooms! As soon as rooms created Homebridge found them!
