### ISSUE TITLE
bug: Error during blind state fetch error

### ISSUE THREAD

**Issue by wjaycalhoun** [apexad/homebridge-mysmartblinds-bridge#11]
Any ideas?  Just checked and I can see the latest firmware is updated as well on the smartblinds.

**Bug**
> ESC[37m[4/17/2020, 8:28:09 PM]ESC[39m ESC[36m[MySmartBlindsBridge]ESC[39m Error during blind state f
etch Error: Sun Room Middle: Cannot read property '0' of null

**Homebridge setup information**
> Node v12.16.2
> HomeBridge 0.4.53

**Logs**
> Error during blind state f
etch Error: Sun Room Middle: Cannot read property '0' of null
    at /usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/index.js:153:31
    at tryCatcher (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

**Comment by apexad** [comment]
Do you only have the 1 blind?  if you have multiple blinds is it doing this for all of them? or just the 1?

**Comment by wjaycalhoun** [comment]
I have 4 blinds.  It doesn’t seem to get past this error to register any of them.

**Comment by apexad** [comment]
Are your blinds assigned to Rooms in the MySmartBlinds app?

**Comment by wjaycalhoun** [comment]
yes.  all assigned to 1 room.

**Comment by apexad** [comment]
MySmartBlinds app or tilt smarthome app?

**Comment by wjaycalhoun** [comment]
MySmartBlinds app

**Comment by apexad** [comment]
Hmm... will have to look at this in more detail in the morning.

**Comment by apexad** [comment]
I'm away from my home and have not tested this myself yet, but hopefully it should work.

I just pushed v1.5.0 which has an allow_debug option (that can also be configured in config ui-x).  If you turn this on, I'm interested in seeing the logs for `DEBUG GetBlindsState` to see what is being sent back from the API (if anything).

**Comment by wjaycalhoun** [comment]
Ah.  That provided the clue.  Sorry, I didn’t realize that the “bridge” was a separate product that i needed buy. :(


[4/18/2020, 1:57:52 PM] [MySmartBlindsBridge] DEBUG GetBlindsState {
  data: { blindsState: null },
  errors: [
    { message: 'No bridges found', locations: [Array], path: [Array] }
  ]
}

**Comment by apexad** [comment]
Yes, you need this:
https://www.mysmartblinds.com/products/smart-hub

**Comment by apexad** [comment]
Alternatively, you can try this plugin:
https://www.npmjs.com/package/homebridge-mysmartblinds
You need to manually configure each blind. The bridge allows you to not have to do it this way.

**Comment by apexad** [comment]
That being said, it’s fascinating to me that you get as far as you did without the bridge. It does actually discover all of the blinds. If anything I could probably make my plugin at least detect no bridge and perhaps print out the necessary information for the plugin that communicates with Bluetooth directly in that I referenced above.

**Comment by wjaycalhoun** [comment]
To that point, not sure if you really need the bridge at all. 


-Will

**Comment by apexad** [comment]
The bridge normally allows you to control the blinds when you are not in bluetooth range/away from home. Obviously the plugin I referenced above communicates with them over bluetooth. Since the homebridge server is the device doing this, it technically does allow you to bypass the need of a bridge.

However, that plugin's setup is obviously much more complex then the setup required by this plugin (which is only a username/password), so the bridge certainly saves you setup time.  Additionally, my plugin has extra features such as low battery reporting and the close up functionality.
