### ISSUE TITLE
incompatible with homebridge-ws due to old agent-base

### ISSUE THREAD

**Issue by apexad** [apexad/homebridge-mysmartblinds-bridge#14]
**Bug or issue information**
> Include as much detail as possible including what is happening and what is expected.

Incompatible with https://www.npmjs.com/package/homebridge-ws
Issue is due to old agent-base being included as a dependency (see logs).

**Homebridge setup information**
> Include if you are running homebridge directly, using HOOBS, etc...  
> Include details about your configuration if needed, but do not include any email address or password.  
> Include node version, if known.

Homebridge 1.10
Node 12

**Logs**
> Include logs here.  Be sure to remove any user identifiable information.

```bash
sudo npm ls -g agent-base
/usr/lib
├─┬ homebridge-mysmartblinds-bridge@1.5.2
│ └─┬ auth0@2.25.1
│   └─┬ rest-facade@1.12.0
│     └─┬ superagent-proxy@2.0.0
│       └─┬ proxy-agent@3.1.1
│         ├── agent-base@4.3.0
│         ├─┬ http-proxy-agent@2.1.0
│         │ └── agent-base@4.3.0  deduped
│         ├─┬ https-proxy-agent@3.0.1
│         │ └── agent-base@4.3.0  deduped
│         ├─┬ pac-proxy-agent@3.0.1
│         │ └── agent-base@4.3.0  deduped
│         └─┬ socks-proxy-agent@4.0.2
│           └── agent-base@4.2.1
```

```bash
[5/19/2020, 19:01:12] [Weather] Milwaukee,WI,USA: warning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:109:11)
    at ClientRequest.once (events.js:431:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/agent-base/patch-core.js:25:22)
    at Object.request (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20)
    at HttpClient.request (/usr/lib/node_modules/homebridge-ws/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HttpClient.get (/usr/lib/node_modules/homebridge-ws/node_modules/homebridge-lib/lib/HttpClient.js:136:17)
    at WsPlatform.weather (/usr/lib/node_modules/homebridge-ws/lib/WsPlatform.js:72:26)
    at WsAccessory.heartbeat (/usr/lib/node_modules/homebridge-ws/lib/WsAccessory.js:60:48)
    at WsAccessory.emit (events.js:323:22)
    at WsAccessory.emit (/usr/lib/node_modules/homebridge-ws/node_modules/homebridge-lib/lib/Delegate.js:172:13)
    at WsPlatform._heartbeat (/usr/lib/node_modules/homebridge-ws/node_modules/homebridge-lib/lib/Platform.js:307:38)
    at WsPlatform._beat (/usr/lib/node_modules/homebridge-ws/node_modules/homebridge-lib/lib/Platform.js:288:42)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-ws/node_modules/homebridge-lib/lib/Platform.js:278:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by apexad** [comment]
Note. this is actually caused by the [auth0](https://github.com/auth0/node-auth0) dependency. I have created issue 490 on that repo for them to look into fixing this.

**Comment by apexad** [comment]
Still no update from auth0 or agent-base

**Comment by apexad** [comment]
Still no update from auth0, several developers have opened this issue in regards to different libraries. I created https://github.com/auth0/node-auth0/issues/490 (which is closed, but other similar linked issues are open still).

**Comment by apexad** [comment]
agent-base has been upgraded to the newest version. This is now resolved.
