### ISSUE TITLE
StatusCodeError: 400 

### ISSUE THREAD

**Issue by gregmichael** [apexad/homebridge-mysmartblinds-bridge#195]
**Bug or issue information**
Unable to login to MySmartBlinds using deprecated auth protocol.

**Logs**

Unhandled rejection StatusCodeError: 400 - {"error":"invalid_request","error_description":"OIDC conformant clients cannot use /oauth/ro"}
    at new StatusCodeError (/homebridge/node_modules/homebridge-mysmartblinds-bridge/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-mysmartblinds-bridge/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-mysmartblinds-bridge/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/homebridge/node_modules/homebridge-mysmartblinds-bridge/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-mysmartblinds-bridge/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-mysmartblinds-bridge/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by name99-org** [comment]
Just FYI this is not a problem with HomeBridge or, exactly, with this plugin, or any updates. The root problem appears to be that the MySmartBlinds server updated/modified the way software authenticates with it, and this plugin has not yet been updated to support the new authentication method.

MySmartBlinds rolled out this change in an extraordinarily kack-handed fashion (at the same time changing a bunch of other things, breaking multiple random functionality, and with zero corporate communication)! However at this point everything else seems to be resolved; the only missing piece is the authentication code in the plugin.

If you look at the various issues associated with this plugin, you'll see one with many more responses than all the others. That's probably the best place to track how things are going.
