### ISSUE TITLE
Broken since last update

### ISSUE THREAD

**Issue by pluddle** [apexad/homebridge-mysmartblinds-bridge#24]
Hello,

Since updating I can't seem to control any blinds, I've removed and re-added the home bridge plugin but still having the same problem. I've posted from the logs below, any help would be great!

`Lounge Lounge Blind setTargetPosition ERROR TypeError: Cannot read property 'data' of undefined
    at /usr/lib/node_modules/homebridge-mysmartblinds-bridge/src/platformAccessory.ts:115:42
    at tryCatcher (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-mysmartblinds-bridge/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)`

**Comment by apexad** [comment]
Please try v2.1.2 (just released) to see if this fixes these issues.

**Comment by apexad** [comment]
If you are still seeing issues after upgrading to v2.1.2 please make sure you have upgraded your NodeJs version to 14.15

**Comment by apexad** [comment]
This should be resolved now.  Please re-open if it is not.
