### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by zackzazula** [apexad/homebridge-mysmartblinds-bridge#56]
**Bug or issue information**

my HOOBS device is able to authenticate, and I see logs indicating that all of my SmartBlinds devices are identified.  However, none if my blinds appear in HomeKit.  When looking at the HOOBS logs it looks like every set of blinds is generating the same error: "Cannot read property '0' of null"

**Homebridge setup information**

HOOBS core version 3.3.2
node v14.15.1
npm v6.14.8

**Logs**

[MySmartBlindsBridge] TypeError: Cannot read property '0' of null
    at /home/hoobs/.hoobs/node_modules/homebridge-mysmartblinds-bridge/src/platform.ts:161:61
    at tryCatcher (/home/hoobs/.hoobs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/hoobs/.hoobs/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/hoobs/.hoobs/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/hoobs/.hoobs/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/hoobs/.hoobs/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/hoobs/.hoobs/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/hoobs/.hoobs/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/hoobs/.hoobs/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/hoobs/.hoobs/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

**Comment by apexad** [comment]
Just to be clear, you are using the bridge, right?  It's a separate hardware device bought from MySmartBlinds/Tilt Smarthome.  Not jus the blinds themselves?

https://www.tiltsmarthome.com/products/smart-hub?variant=31506970148929

**Comment by apexad** [comment]
After a quick review of https://github.com/apexad/homebridge-mysmartblinds-bridge/issues/11 I am sure you do not have a bridge, but I want to put in a better fix for this to catch this error and give a better error message.

**Comment by zackzazula** [comment]
I am using the bridge you included a link to.

**Comment by apexad** [comment]
Very strange! Not sure what would cause this then. I will at the very least attempt to handle this error better as I mentioned, but just to confirm, control and everything works from the app?

**Comment by zackzazula** [comment]
Yes.  I have 16 individual blinds which are in 7 locations - all managed and controlled though the MySmartBlinds app.

**Comment by apexad** [comment]
Sorry I did not get back to you on this, too a bit of a homebridge plugin writing break.

So, just to be clear I am not entirely sure how to fix this without a major re-write of the way I am requesting blind information (single blind vs all blinds) which is the solve for #64, but for now I can at least catch the error and handle it better.  Working on this now.

**Comment by apexad** [comment]
Actually #38 will have progress on batch re-factor which should solve general connection issues.
